apiVersion: v1
kind: Service
metadata:
  name: promtest
  labels:
    app: promtest
    run: promtest
spec:
  ports:
  - name: promtest-port
    port: 9091
    protocol: TCP
    targetPort: 80
  selector:
    app: promtest
  type: NodePort